=== bartongroup/Slivka/utils/FormSchema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="form">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="field" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="label" type="xs:string" />
              <xs:element name="description" type="xs:string" />
              <xs:choice>
                <xs:sequence>
                  <xs:choice>
                    <xs:element name="integerValue">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="min" type="xs:integer" minOccurs="0" />
                          <xs:element name="max" type="xs:integer" minOccurs="0" />
                          <xs:element name="default" type="xs:integer" minOccurs="0" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="decimalValue">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:choice minOccurs="0">
                            <xs:element name="minInclusive" type="xs:decimal" />
                            <xs:element name="minExclusive" type="xs:decimal" />
                          </xs:choice>
                          <xs:choice minOccurs="0">
                            <xs:element name="maxInclusive" type="xs:decimal" />
                            <xs:element name="maxExclusive" type="xs:decimal" />
                          </xs:choice>
                          <xs:element name="default" type="xs:decimal" minOccurs="0" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="fileValue">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="extension" type="extension" minOccurs="0" />
                          <xs:element name="minSize" type="xs:positiveInteger" minOccurs="0" />
                          <xs:element name="maxSize" type="xs:positiveInteger" minOccurs="0" />
                          <xs:element name="default" type="xs:string" minOccurs="0" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="textValue">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="minLength" type="xs:nonNegativeInteger" minOccurs="0" />
                          <xs:element name="maxLength" type="xs:nonNegativeInteger" minOccurs="0" />
                          <xs:element name="default" type="xs:string" minOccurs="0" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="booleanValue">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="default" type="xs:boolean" minOccurs="0" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:choice>
                </xs:sequence>
                <xs:element name="select">
                  <xs:complexType>
                    <xs:sequence minOccurs="1" maxOccurs="unbounded">
                      <xs:element name="choice">
                        <xs:complexType>
                          <xs:sequence>
                            <xs:element name="label" type="xs:string" />
                            <xs:element name="description" minOccurs="0" type="xs:string" />
                            <xs:element name="value" type="param" />
                          </xs:sequence>
                        </xs:complexType>
                      </xs:element>
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
              </xs:choice>
            </xs:sequence>
            <xs:attribute name="name" type="idString" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>

    <xs:unique name="uniqueIdForEachOption">
      <xs:selector xpath="option" />
      <xs:field xpath="@id" />
    </xs:unique>

  </xs:element>

  <xs:simpleType name="idString">
    <xs:restriction base="xs:string">
      <xs:minLength value="2" />
      <xs:maxLength value="16" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="param">
    <xs:restriction base="xs:string">
      <xs:pattern value="--?\w[\w-]*([ =]$\{value\})?" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="extension">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z0-9]" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="empty">
    <xs:restriction base="xs:string">
      <xs:maxLength value="0" />
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== bartongroup/Slivka/config/DummyForm.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>

<form
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="utils/FormSchema.xsd" >


    <field name="return">
        <label>Return code</label>
        <description>code returned by the program</description>
        <integerValue>
            <default>0</default>
        </integerValue>
    </field>

    <field name="long">
        <label>Long computation</label>
        <description>extends execution to 5 sec</description>
        <booleanValue>
            <default>false</default>
        </booleanValue>
    </field>

    <field name="very_long">
        <label>Very long computation</label>
        <description>extends execution to 30 seconds</description>
        <booleanValue>
            <default>false</default>
        </booleanValue>
    </field>

    <field name="foo">
        <label>Foo</label>
        <description>foo variable</description>
        <textValue>
            <minLength>2</minLength>
            <maxLength>10</maxLength>
            <default>Foo</default>
        </textValue>
    </field>

    <field name="error">
        <label>Error</label>
        <description>Generates an error</description>
        <booleanValue>
            <default>true</default>
        </booleanValue>
    </field>

    <field name="choice">
        <label>Choice</label>
        <description>Choose wisely</description>
        <select>
            <choice>
                <label>A</label>
                <value>-a</value>
            </choice>
            <choice>
                <label>B</label>
                <description>Not a correct answer</description>
                <value>-b</value>
            </choice>
            <choice>
                <label>C</label>
                <value>-c</value>
            </choice>
        </select>
    </field>

</form>
